---
- name: backoffice
  hosts: backoffice
  remote_user: ubuntu
  become: true
  vars:
    app_user: ubuntu

  tasks:
    - import_tasks: tasks/prometheus.yaml

  handlers:
    - name: prometheus is restarted
      service:
        name: prometheus
        state: restarted

    - name: prometheus is reloaded
      service:
        name: prometheus
        state: reloaded
