---
- name: backoffice
  hosts: backoffice
  remote_user: ubuntu
  become: true
  vars:
    app_user: ubuntu

  tasks:
    - import_tasks: tasks/apt-update.yaml
    - import_tasks: tasks/systemd.yaml
    - import_tasks: tasks/prometheus.yaml
    - import_tasks: tasks/uwsgi.yaml

  handlers:
    - name: prometheus is restarted
      service:
        name: prometheus
        state: restarted

    - name: prometheus is reloaded
      service:
        name: prometheus
        state: reloaded

    - name: systemd is reloaded
      systemd:
        daemon_reload: yes

    - name: uwsgi is restarted
      service:
        name: uwsgi
        state: restarted

    - name: uwsgi is reloaded
      service:
        name: uwsgi
        state: reloaded
