---
- name: backoffice
  hosts: development, production
  remote_user: ubuntu
  become: true
  vars:
    app_user: ubuntu
    uwsgi_apps:
      - api-production
      - api-testing
      - husky-musher

  tasks:
    - import_tasks: tasks/registrations.yaml
    - import_tasks: tasks/apt-update.yaml
<<<<<<< HEAD
    - import_tasks: tasks/ssh-keys.yaml
=======
      tags: [ init, operations, packages, apt ]
    - import_tasks: tasks/postgres.yaml
      tags: [ never, init, postgres ]
    - import_tasks: tasks/python.yaml
      tags: [ never, init, python ]
    - import_tasks: tasks/backoffice-repos.yaml
      tags: [ init, operations, packages, repos ]
    - import_tasks: tasks/backoffice-pipenv.yaml
      tags: [ init, operations, packages, pipenv ]
    - import_tasks: tasks/systemd.yaml
      tags: [ init, operations, packages, systemd ]
    - import_tasks: tasks/switchboard.yaml
      tags: [ init, operations, packages, switchboard ]
    - import_tasks: tasks/husky-musher.yaml
      tags: [ init, operations, packages, musher ]
>>>>>>> b022f82 (Checkout all Backoffice Repos in `/opt` directory)
    - import_tasks: tasks/systemd.yaml
    - import_tasks: tasks/prometheus.yaml
    - import_tasks: tasks/promtail.yaml
    - import_tasks: tasks/postgres.yaml
    - import_tasks: tasks/python.yaml
    - import_tasks: tasks/uwsgi.yaml
    - import_tasks: tasks/backoffice-repos.yaml
    - import_tasks: tasks/apache2.yaml
    - import_tasks: tasks/certbot.yaml
    - import_tasks: tasks/dev-ssl-cert.yaml
      when: development
    - import_tasks: tasks/prod-ssl-cert.yaml
      when: production
    - import_tasks: tasks/backoffice-pipenv.yaml
    - import_tasks: tasks/switchboard.yaml

  handlers:
    - name: systemd units are re-read from disk
      systemd:
        daemon_reload: yes

    - name: prometheus is restarted
      service:
        name: prometheus
        state: restarted

    - name: prometheus is reloaded
      service:
        name: prometheus
        state: reloaded

    - name: prometheus-node-exporter is restarted
      service:
        name: prometheus-node-exporter
        state: restarted

    - name: promtail is restarted
      service:
        name: promtail
        state: restarted
