---
- name: backoffice
  hosts: backoffice
  remote_user: ubuntu
  become: true
  vars:
    app_user: ubuntu
    uwsgi_apps:
      - api-production
      - api-testing
      - husky-musher

  tasks:
    - import_tasks: tasks/apt-update.yaml
    - import_tasks: tasks/apache.yaml
    - import_tasks: tasks/systemd.yaml
    - import_tasks: tasks/prometheus.yaml
    - import_tasks: tasks/uwsgi.yaml
    - import_tasks: tasks/switchboard.yaml
    - import_tasks: tasks/promtail.yaml

  handlers:
    - name: systemd units are re-read from disk
      systemd:
        daemon_reload: yes

    - name: apache is restarted
      service:
        name: apache2
        state: restarted

    - name: apache is reloaded
      service:
        name: apache2
        state: reloaded

    - name: prometheus is restarted
      service:
        name: prometheus
        state: restarted

    - name: prometheus is reloaded
      service:
        name: prometheus
        state: reloaded

    - name: promtail is restarted
      service:
        name: promtail
        state: restarted
