# TODO: for production:
#
# - hosts: backoffice.seattleflu.org
#   remote_user: ubuntu
#
# See https://www.middlewareinventory.com/blog/run-ansible-playbook-locally/
---
  - hosts: localhost
    connection: local
    vars:
      environment_name: id3c-restricted
    tasks:
    - name: Ensure the repo has been cloned locally
      git:
        repo: 'https://github.com/seattleflu/backoffice.git'
        dest: /opt/backoffice
        clone: no
        update: no

    - name: Create a new branch
      shell: "git checkout -b {{ environment_name }}"
