# TODO: for production:
#
# - hosts: backoffice.seattleflu.org
#   remote_user: ubuntu
#   vars:
#     backoffice_destination: /opt/backoffice
#
# See https://www.middlewareinventory.com/blog/run-ansible-playbook-locally/
---
  - hosts: localhost
    connection: local
    vars:
      environment_name: id3c-restricted
      backoffice_destination: ~/seattleflu/backoffice  # TODO
    tasks:
    - name: Ensure the repo has been cloned locally and is updated
      git:
        repo: 'https://github.com/seattleflu/backoffice.git'
        dest: "{{ backoffice_destination }}"

    - name: Change directories and create new branch named after environment name «{{ environment_name }}»
      shell: "cd {{backoffice_destination}} && git checkout -b {{ environment_name }}"
