---
- name: installed apache httpd
  apt:
    update_cache: yes
    package:
      - apache2
      - libapache2-mod-proxy-uwsgi
      - libapache2-mod-wsgi-py3
    install_recommends: yes

- name: checked out latest version of apache2 repository
  become: yes
  become_user: '{{app_user}}'
  git:
    repo: 'git@github.com:seattleflu/backoffice-apache2.git'
    dest: /opt/backoffice-apache2
    accept_hostkey: yes
    force: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: installed the latest version of the apache2 repository
  become: yes
  copy:
    remote_src: yes
    src: /opt/backoffice-apache2/
    dest: /etc/apache2
    local_follow: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: apache2 temp directory in /opt was removed
  file:
    state: absent
    path: /opt/backoffice-apache2/

- name: permissions on the apache directory are set
  file:
    path: /etc/apache2
    state: directory
    owner: 'root'
    group: 'root'
    recurse: yes
