---
- name: permissions on the backoffice directory are set
  file:
    path: /opt/backoffice
    state: directory
    owner: '{{app_user}}'
    group: '{{app_user}}'
    recurse: yes

- name: Check out latest version of backoffice repository
  become: yes
  become_user: '{{app_user}}'
  git:
    repo: 'git@github.com:/seattleflu/backoffice.git'
    dest: /opt/backoffice
    accept_hostkey: yes
    force: yes
