---
- name: Set permissions on backoffice directory
  file:
    path: /opt/backoffice
    state: directory
    owner: '{{app_user}}'
    group: '{{app_user}}'
    recurse: yes

- name: Check out latest version of backoffice repository
  become: yes
  become_user: '{{app_user}}'
  git:
    repo: 'git@github.com:/seattleflu/backoffice.git'
    dest: /opt/backoffice
    accept_hostkey: yes
    force: yes

- name: Set permissions on switchboard directory
  file:
    path: /opt/sfs-switchboard
    state: directory
    owner: '{{app_user}}'
    group: '{{app_user}}'
    recurse: yes

- name: Check out latest version of switchboard repository
  become: yes
  become_user: '{{app_user}}'
  git:
    repo: 'git@github.com:/seattleflu/switchboard.git'
    dest: /opt/sfs-switchboard
    accept_hostkey: yes
    force: yes

- name: Check out latest version of backoffice-apache2 repository
  git:
    repo: 'git@github.com:/seattleflu/backoffice-apache2.git'
    dest: /etc/backoffice-apache2
    accept_hostkey: yes
    force: yes

