---
- name: id3c-production pipenv was synced
  become: yes
  become_user: '{{app_user}}'
  environment:
    PATH: /opt/python/current/bin:{{ ansible_env.PATH }}
  command:
    chdir: /opt/backoffice/id3c-production
    cmd: "pipenv sync"

- name: id3c-testing pipenv was synced
  become: yes
  become_user: '{{app_user}}'
  environment:
    PATH: /opt/python/current/bin:{{ ansible_env.PATH }}
  command:
    chdir: /opt/backoffice/id3c-testing
    cmd: "pipenv sync"
