---
- name: create id3c-production pipenv
  become: yes
  become_user: '{{app_user}}'
  environment:
    PATH: /opt/python/current/bin:{{ ansible_env.PATH }}
  command:
    chdir: /opt/backoffice/id3c-production
    cmd: "pipenv sync"

- name: create id3c-testing pipenv
  become: yes
  become_user: '{{app_user}}'
  environment:
    PATH: /opt/python/current/bin:{{ ansible_env.PATH }}
  command:
    chdir: /opt/backoffice/id3c-testing
    cmd: "pipenv sync"

- name: create wa-doh-linelists pipenv
  become: yes
  become_user: '{{app_user}}'
  environment:
    PATH: /opt/python/current/bin:{{ ansible_env.PATH }}
  command:
    chdir: /opt/backoffice/wa-doh-linelists
    cmd: "pipenv sync"
