---
- name: the self-signed cert directory was created
  file:
    path: /etc/letsencrypt/live/backoffice.seattleflu.org
    state: directory

- name: the self-signed cert archive directory was created
  file:
    path: /etc/letsencrypt/archive/backoffice.seattleflu.org
    state: directory

- name: Python modules required to create a certificate were installed
  apt:
    update_cache: yes
    package:
      - python3-openssl

- name: an OpenSSL private key was generated
  openssl_privatekey:
    path: "/etc/letsencrypt/live/backoffice.seattleflu.org/privkey.pem"

- name: an OpenSSL Certificate Signing Request with Subject information was generated
  openssl_csr:
    path: "/etc/letsencrypt/live/backoffice.seattleflu.org/csr.pem"
    privatekey_path: "/etc/letsencrypt/live/backoffice.seattleflu.org/privkey.pem"
    country_name: "US"
    organization_name: "UW BBI Dev Team"
    email_address: "developer@example.com"
    common_name: "backoffice-dev"

- name: a Self Signed OpenSSL certificate was generated
  openssl_certificate:
    path: "/etc/letsencrypt/live/backoffice.seattleflu.org/fullchain.pem"
    privatekey_path: "/etc/letsencrypt/live/backoffice.seattleflu.org/privkey.pem"
    csr_path: "/etc/letsencrypt/live/backoffice.seattleflu.org/csr.pem"
    provider: selfsigned
