---
- name: check if Postgres PGDG key is already installed
  stat:
    path: /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg
  register: pgdg_key_path

- name: download upstream Postgres GPG keys
  when: not pgdg_key_path.stat.exists
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /tmp
    checksum: sha1:403374e8f22266f67fe14b79b8257491dce75af7

- name: install upstream Postgres GPG keys
  when: not pgdg_key_path.stat.exists
  command:
    cmd: /usr/bin/gpg -o /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --dearmor /tmp/ACCC4CF8.asc

- name: ensure apt sources list contains PGDG repo
  lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    create: yes
    mode: 0644
    line: deb http://apt.postgresql.org/pub/repos/apt {{ansible_lsb.codename}}-pgdg main

- name: install Postgres client
  apt:
    update_cache: yes
    pkg:
      - postgresql-client-{{postgres_version}}

- name: install Postgres development headers for psycopg2
  apt:
    update_cache: yes
    pkg:
      - libpq-dev

- name: added backoffice pg_service file
  copy:
    src: files/etc/postgres/.pg_service.conf
    dest: ~/.pg_service.conf
    owner: ubuntu
    group: ubuntu
    mode: ug=r,o=

# don't install our passwords on development environments
- name: postgres password file is installed
  when: not development
  copy:
    src: files/etc/postgres/.pgpass
    dest: ~/.pgpass
    owner: ubuntu
    group: ubuntu
    mode: u=rw,go=
