---

- name: unzip is installed
  apt:
    package:
      - unzip

- name: promtail directory exists
  file:
    path: /etc/promtail
    state: directory

- name: promtail is downloaded
  unarchive:
    remote_src: yes
    src: https://github.com/grafana/loki/releases/download/v2.1.0/promtail-linux-amd64.zip
    dest: /usr/local/bin
    owner: root
    group: root
    mode: u=rwX,go=rX
    creates: /usr/local/bin/promtail-linux-amd64

- name: promtail is installed
  file:
    state: link
    path: /usr/local/bin/promtail
    src: promtail-linux-amd64

- name: promtail settings are configured
  template:
    src: files/etc/promtail/promtail.yml
    dest: /etc/promtail/promtail.yml
  notify:
    - promtail is restarted

- name: grafana api key is installed
  copy:
    src: files/etc/promtail/grafana-cloud-api-key
    dest: /etc/promtail/grafana-cloud-api-key
    owner: root
    group: root
    mode: ug=r,o=
