---
- name: python basics are installed
  apt:
    package:
      - python3
      - python3-dev
      - python3-pip
      - python3-venv

- name: pipenv is installed
  pip:
    name:
      - pipenv==2018.11.26

- name: pipenv is configured
  lineinfile:
    path: /etc/environment
    regexp: '^PIPENV_VENV_IN_PROJECT='
    line: 'PIPENV_VENV_IN_PROJECT=1'
