---
- name: enforce permissions on root's SSH directory
  file:
    path: /root/.ssh
    state: directory
    mode: go-rwx
    recurse: yes

- name: enforce permissions on {{app_user}}'s SSH directory
  file:
    path: /home/{{app_user}}/.ssh
    state: directory
    owner: '{{app_user}}'
    group: '{{app_user}}'
    mode: go-rwx
    recurse: yes
