---
- name: ensure acl tools are installed
  apt:
    package:
      - acl

- name: switchboard data dir owner/group/mode is set
  file:
    path: &data_dir /opt/sfs-switchboard/data
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: ug=rwx,o=rx
    state: directory

- name: switchboard data dir ACLs are set
  loop:
    - "{{app_user}}"
    - nobody
  ansible.posix.acl:
    path: *data_dir
    etype: user
    entity: "{{item}}"
    permissions: rwx
    state: present

- name: switchboard data dir default ACLs are set
  loop:
    - "{{app_user}}"
    - nobody
  ansible.posix.acl:
    path: *data_dir
    default: true
    etype: user
    entity: "{{item}}"
    permissions: rwX
    state: present

- name: install switchboard virtualenv
  become: yes
  become_user: "{{app_user}}"
  command:
    chdir: /opt/sfs-switchboard
    cmd: make venv
   
