---
- name: permissions on switchboard directory are set
  file:
    path: /opt/sfs-switchboard
    state: directory
    owner: '{{app_user}}'
    group: '{{app_user}}'
    recurse: yes

- name: checked out latest version of switchboard repository
  become: yes
  become_user: '{{app_user}}'
  git:
    repo: 'git@github.com:seattleflu/switchboard.git'
    dest: /opt/sfs-switchboard
    accept_hostkey: yes
    force: yes

- name: switchboard data dir owner/group/mode is set
  file:
    path: &data_dir /opt/sfs-switchboard/data
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: ug=rwx,o=rx
    state: directory

- name: switchboard data dir ACLs are set
  loop:
    - "{{app_user}}"
    - nobody
  ansible.posix.acl:
    path: *data_dir
    etype: user
    entity: "{{item}}"
    permissions: rwx
    state: present

- name: switchboard data dir default ACLs are set
  loop:
    - "{{app_user}}"
    - nobody
  ansible.posix.acl:
    path: *data_dir
    default: true
    etype: user
    entity: "{{item}}"
    permissions: rwX
    state: present

- name: sqllite nogroup/noowner file paths were found
  find:
    paths: /opt/sfs-switchboard/data
    file_type: file
    patterns: "sfs-redcap.sqlite-*"
  register: filelist

- name: switchboard data dir group and owners are set
  file:
    path: '{{ item.path }}'
    state: file
    owner: nobody
    group: nogroup
  with_items: '{{ filelist.files }}'

- name: switchboard virtualenv was installed
  become: yes
  become_user: "{{app_user}}"
  environment:
    PATH: /opt/python/current/bin:{{ansible_env.PATH}}
  shell:
    chdir: /opt/sfs-switchboard
    cmd: make venv
