---
- name: systemd units are installed
  copy:
    src: files/etc/systemd/system/
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: u=rw,go=r
  notify:
    - systemd units are re-read from disk
