---
- name: systemd units are installed
  copy:
    src: files/etc/systemd/system/
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: u=rw,go=r

- name: metabase unit link is created
  file:
    src: /opt/backoffice/metabase/metabase.service
    dest: /etc/systemd/system/metabase.service
    state: link
    force: yes

- name: lab labels unit link is created
  file:
    src: /opt/backoffice/lab-labels/lab-labels.service
    dest: /etc/systemd/system/lab-labels.service
    state: link
    force: yes
