---
- name: uwsgi is installed
  apt:
    package:
      - uwsgi
      - uwsgi-plugin-python3
    update_cache: true

- name: uwsgi is enabled
  service:
    name: uwsgi
    enabled: yes
    state: started

- name: uwsgi base config exists
  copy:
    remote_src: true
    src: /usr/share/uwsgi/conf/default.ini
    dest: /etc/uwsgi/base.ini
    force: no
    backup: yes

- name: uwsgi default invocation is configured
  lineinfile:
    path: /etc/default/uwsgi
    regexp: '^INHERITED_CONFIG='
    line: 'INHERITED_CONFIG=/etc/uwsgi/base.ini'
  notify:
    # Restart not reload since the actual options used to invoke uWSGI changed,
    # not just the contents of its config files.
    - uwsgi is restarted
