---
- name: uwsgi is installed in system Python
  when: not custom_python_path.stat.exists
  apt:
    package:
      - uwsgi
      - uwsgi-plugin-python3

- name: uwsgi is installed in /opt/python
  when: custom_python_path.stat.exists
  pip:
    executable: "{{custom_python_path.stat.path}}/pip3"
    name:
      - uwsgi

- name: uwsgi config directory exists
  file:
    path: /etc/uwsgi
    state: directory
    mode: 0755

- name: uwsgi base config exists
  copy:
    src: files/etc/uwsgi/base.ini
    dest: /etc/uwsgi/base.ini
    owner: root
    group: root
    mode: ugo=r

- name: uwsgi app configs exists
  loop: "{{ uwsgi_apps }}"
  copy:
    src: "files/etc/uwsgi/apps-available/{{ item }}.ini"
    dest: /etc/uwsgi/apps-available/
    owner: root
    group: root
    mode: ugo=r

- name: uwsgi app logs readable by adm group
  file:
    path: /var/log/uwsgi/app/
    state: directory
    owner: root
    group: adm
    mode: u=rwX,g=rX,o=
    recurse: yes

- name: uwsgi app logs default to adm group
  file:
    path: /var/log/uwsgi/app/
    state: directory
    owner: root
    group: adm
    mode: u=rwx,go=rxs
